name: Scrape PHIVOLCS Earthquake Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas certifi

      - name: Run scraper
        run: python scraper/scrape_phivolcs.py

      - name: Commit updated CSV
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add phivolcs_earthquakes.csv
          git diff --cached --quiet || (git commit -m "Update earthquake data" && git push)
